import Head from 'next/head'
import Footermain from '../components/FooterMain';
import NavBar from "../components/NavBar";
import NavNavbarMobol from "../components/NavNavbarMobol";
import NavnonavsBar from "../components/NavnonavsBar";

export default function Home() {
  return (
    <div  className="relative h-screen ">
      <Head>
        <title>CryptoMap </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar 
        className="sticky top-0 overflow-hidden" 
     />
         <NavnonavsBar />
   <NavNavbarMobol
         className="sticky top-0 overflow-hidden" 
         home="border-b-4 border-red-500"  
   /> 










<Footermain className=""/>


    </div>
  )
}
