import Head from "next/head";
import NavBar from "../components/NavBar";
import NavNavbarMobol from "../components/NavNavbarMobol";

export default function Home() {
  return (
    <div className='relative h-screen '>
      <Head>
        <title>CryptoMap </title>
        <meta name='propeller' content='c944d701fc1056a48a801e54792c44a3' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavNavbarMobol
        className='sticky top-0 overflow-hidden'
        home='border-b-4 border-red-500'
      />
    </div>
  );
}
